---
- hosts: "{{ target }}" #Variable
  remote_user: snipeit
  become: true
  vars:
    ansible_port: "{{ ssh_port }}"
  vars_files:
    - host_vars/orb
    - host_vars/encrypted_vars
  roles:
    - geerlingguy.firewall
    - geerlingguy.docker
    - users
    - env_file
    - snipeit_docker
    - permissions
 