---
- hosts: "{{ target }}" #Variable
  remote_user: snipeit
  become: true
  vars:
    ansible_port: "{{ ssh_port | default('22') }}"
  vars_files:
    - host_vars/orb
    - host_vars/encrypted_vars
  roles:
    - apt_upgrade
 