---
- hosts: "{{ target }}" #Variable
  remote_user: dirk
  become: true
  vars:
    ansible_port: "{{ ssh_port | default('22') }}"
  vars_files:
    - host_vars/orb
    - host_vars/encrypted_vars
  roles:
    - users
    - ssh
    - aliases
    - tools
    - geerlingguy.firewall
    - geerlingguy.docker
    - env_file
    - snipeit_docker
    - permissions
 