---
- hosts: all
  remote_user: snipeit
  become: true
  vars:
    ansible_port: 22
  vars_files:
    - host_vars/security_vars
    - host_vars/encrypted_vars
  roles:
    - apt_upgrade
    - application
    - migration
