---
#- name: Check if "installimage" script exists
#  stat:
#    path: #Pfad
#  register: stat_result
#- block:
#    - debug:
#        msg: "installimage script not found."
#    - meta: end_play # beendet playbook
#  when: stat_result.stat.exists == false
#
#- name: Execute installimage
#  shell: # command
#
#- name: Rebooting...
#  shell: reboot